name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.9
repository: https://github.com/isar-community/isar
homepage: https://isar.dev
publish_to: https://pub.isar-community.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.7.0
  build: ^3.0.0
  dart_style: ^3.1.1
  dartx: ^1.2.0
  glob: ^2.1.3
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev
  path: ^1.9.1
  source_gen: ^3.0.0
  xxh3: ^1.2.0

dev_dependencies:
  build_test: any
  matcher: ^0.12.17
  flutter_lints: ^6.0.0
